@startuml
enum Selection {
+ TRUE
+ FALSE
}

class Quiz {
- questionCounter : int
- name : String
-questions[] : Question
+ addQuestion(Question question) : void
+ getGrade(int[] answers) : double
+ getQuizPoints() : int
}

class Student {
- grade : double
- name : String
- quiz : Quiz
+ setQuiz(Quiz quiz) : void
+ answer() : void
+ printGrade() : String
}

abstract class Question {
- points : int
- statement : String
- options[] : Option
+ grade(int answer) : double
}

class MultipleChoiceQuestion

class TrueFalseQuestion {
+ parseToOptions(Selection selection) : Option[]
}

class Option {
- statement : Object
}

class CorrectOption

MultipleChoiceQuestion --|> Question
TrueFalseQuestion --|> Question

CorrectOption --|> Option
@enduml